# Generated by Django 4.2 on 2023-04-21 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='new',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('selling_price', models.PositiveBigIntegerField()),
                ('discription', models.TextField()),
                ('category', models.CharField(choices=[('TO', 'Top'), ('SK', 'Skirt'), ('PA', 'Pants'), ('SH', 'Shorts')], max_length=2)),
                ('size', models.CharField(choices=[('Xs', 'Xs'), ('S', 'S'), ('M', 'M'), ('L', 'L')], max_length=2)),
                ('color', models.CharField(choices=[('black', 'black'), ('navy', 'navy'), ('gray', 'gray'), ('yellow', 'yellow'), ('LB', 'light blue'), ('red', 'red'), ('white', 'white')], max_length=10)),
                ('product_image', models.ImageField(upload_to='images')),
            ],
        ),
    ]
