# Generated by Django 4.2 on 2023-04-23 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_alter_order_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='rezorpay_order_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.order'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='rezorpay_payment_status',
            field=models.CharField(blank=True, choices=[('Processing', 'Processing'), ('Succeeded', 'Succeeded'), ('Failed', 'Failed')], max_length=20, null=True),
        ),
    ]
