# Generated by Django 4.2 on 2023-04-25 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_alter_order_user_alter_payment_amount_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='bestseller',
        ),
        migrations.DeleteModel(
            name='new',
        ),
    ]
