# Generated by Django 4.2 on 2023-04-27 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_transaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='slug',
        ),
        migrations.AlterField(
            model_name='order',
            name='product_image',
            field=models.ImageField(default='default_value', upload_to='images'),
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
