# Generated by Django 4.2 on 2023-04-29 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_payment_remove_order_transaction_order_order_ids_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='product_image',
            field=models.ImageField(upload_to='images'),
        ),
    ]
